### ISSUE TITLE
Really really short vandelay question

### ISSUE THREAD

**Issue by mnieber** [ericbiewener/log-all-the-things#3]
Hi Eric, sorry to bother you here, I couldn't reach you anymore on the vandelay repo.

I just wanted to ask: did you find something better than vandelay for importing python symbols in vscode? If so, which tool is it?
I may indeed fork vandelay, it's essential for me, and it would be nice if I can still fix my issue.

Many thanks for a great tool,
Maarten Nieber

**Comment by ericbiewener** [comment]
No, I just haven't been writing Python for the last ~5 years.
